services:
  localstack:
    image: localstack/localstack:3.8
    container_name: localstack

    ports:
      - "4568:4568"

    environment:
      - SERVICES=s3
      - DEBUG=1

  streamlit:
    build: .
    container_name: streamlit-app

    ports:
      - "8501:8501"

    env_file:
      - .env

    depends_on:
      - localstack